version: "3"

services:
  web:
    image: nodeweb:latest
    build:
      context: ./web
    expose:
      - 9000
    ports:
      - "9000:9000"
    environment:
      PORT: '9000'
      API_HOST: 'http://api:8000'
  api:
    image: nodeapi:latest
    build:
      context: ./api
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB: 'db'
      DBUSER: 'appuser'
      DBPASS: 'apppass'
      DBHOST: 'db'
      DBPORT: 5432

  db:
    image: postgres
    environment:
      POSTGRES_USER: 'appuser'
      POSTGRES_PASSWORD: 'apppass'
      POSTGRES_DB: 'db'
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
